name: english_numerals
description: A package to convert numbers to and from their English written form, with null safety and no dependency on flutter.
version: 1.0.0
homepage: https://github.com/gbassisp/english_numerals

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  meta: ^1.0.0

dev_dependencies:
  test: ^1.16.0
  very_good_analysis: 
