name: english_numerals
description: A package to convert numbers to their English written form, with null safety and no dependency on flutter.
version: 0.0.1
homepage: https://github.com/gbassisp/english_numerals

environment:
  sdk: '>=2.15.0 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
